### ISSUE TITLE
[v0.7] Update Dependency Version Ranges

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#2813]
Try to update the supported ranges of the following packages prior to v0.7 release:

- [x] numpy -> test 1.24.x (consider upper capping to `<1.27` if no numpy warnings in 1.24 [[Reasoning](https://github.com/autogluon/autogluon/issues/612#issuecomment-1413133895)]) #2834
- [x] pandas -> Already latest
- [x] scikit-learn -> test 1.2.x #2834
- [x] scipy -> test 1.10.0 #2834
- [x] xgboost -> Already latest
- [x] catboost -> Already latest, sticking to 1.1, 1.2 may release soon but not enough time to test
- [x] lightgbm -> Already latest
- [x] fastai -> Already latest
- [x] torch -> Updated to latest `>=1.9,<1.14`
- [x] networkx -> skip upgrade to 3.0 (just released), wait until AG 0.8
- [x] boto3 -> currently uncapped, note: for 0.8 we will want to set version range (esp lower bound). Tracking: #2814 
- [x] psutil -> Already latest
- [x] Pillow -> Already latest
- [x] timm -> Already latest
- [x] dask -> Removed, not used
- [x] distributed -> Removed, not used
- [x] pillow -> update range to upper bound `<9.6` (Tracking: #2818)

**Comment by Innixma** [comment]
Awaiting running version change test until CatBoost 1.2 is released.

**Comment by Innixma** [comment]
CatBoost 1.2 appears to be delayed, so we are instead going to continue using 1.1 for AG v0.7 release.

The follow submodules are fully updated:

- common
- core
- features
- tabular
- multimodal

The following submodules are still awaiting dependency updates:

- timeseries #2831
- eda #2846
