### ISSUE TITLE
1.1 Release Tracker

### ISSUE THREAD

**Issue by Innixma** [autogluon/autogluon#4027]
High Priority 1.1 Release Items

- [x] #3613
- [x] #3774 @AnirudhDagar @prateekdesai04 (post ray upgrade: Fix #3920 @suzhoum; close #3807; close #2687)
- [x] Fix Platform Tests hanging issue for tabular @prateekdesai04
- [x] Various Tabular Dependency Upgrades #4024 @Innixma
- [x] Tabular Refit Stability Enhancement #3977 @Innixma
- [x] Time series feature importance #4033 @canerturkmen 
- [x] Time series: categorical covariates in all models #4037 @shchur 
- [x] Time series: preprocess real-valued features #4042 @shchur
- [x] Pandas 2.2 Support #4079 @Innixma @shchur 
- [x] Fix time series platform tests - chronos failures on windows platform @canerturkmen @AnirudhDagar 
- [x] Fix time series platform tests - test_models.py failure, in ubuntu-3.8 and macos-3.8 #4049 @prateekdesai04 @shchur 
- [x] Fix tabular platform tests failures for Windows (observed post Ray upgrade) #4045 @tonyhoo 
- [x] #4048
- [x] #4066 @Innixma
- [x] #4000 @tonyhoo 
- [x] #4065
- [x] #3800 @tonyhoo @zhiqiangdon 
- [x] #4098 @canerturkmen @shchur
- [x] #4089 @Innixma 
- [x] Benchmark Results Comparison @prateekdesai04 @Innixma 
- [x] #4109 @suzhoum @Innixma
- [x] #4111 @Innixma 
- [ ] Fix TensorRT Tutorial Exception @suzhoum

**Comment by ddelange** [comment]
@AnirudhDagar will tensorrt / `optimize_for_inference` still be re-enabled for py 3.11 in the 1.1 release?

**Comment by Innixma** [comment]
@ddelange Looks like it is not be in 1.1 release, unsure if there is a reason. I created an issue to track: #4130, we can see if it can added in the next micro release.
